(function(){
const content=window.DSA_CONTENT;const progressKey="dsa-studio-progress";const progress=new Set(JSON.parse(localStorage.getItem(progressKey)||"[]"));const $=s=>document.querySelector(s);
function esc(t){return t.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function label(v){return {"high-school":"High school",college:"College",professional:"Professional"}[v]||v;}
function save(){localStorage.setItem(progressKey,JSON.stringify([...progress]));renderProgress();}
function renderProgress(){const total=content.structures.length+content.algorithms.length;const pct=total?Math.round(progress.size/total*100):0;$("#progressText").textContent=`${pct}%`;$("#progressFill").style.width=`${pct}%`;$("#todayList").innerHTML=[...content.structures,...content.algorithms].filter(i=>!progress.has(i[0])).slice(0,5).map(i=>`<li><span>${i[1]}</span><span>${label(i[3])}</span></li>`).join("");}
function renderFoundations(){$("#foundationGrid").innerHTML=content.foundations.map(i=>`<article class="card"><span class="pill green">Foundation</span><h3>${i.title}</h3><p>${i.text}</p><p><strong>Example:</strong> ${i.example}</p></article>`).join("");}
function card(i,type){const done=progress.has(i[0]);return `<article class="card"><div class="meta"><span class="pill ${type==="structure"?"blue":"yellow"}">${type}</span><span class="pill">${label(i[3])}</span></div><h3>${i[1]}</h3><p>${i[2]}</p>${i[4]?`<p>${i[4]}</p>`:""}<div class="button-row"><button class="button topic-action" data-progress-id="${i[0]}">${done?"Marked done":"Mark done"}</button><a class="button" href="#topic-lab" data-open-topic="${i[0]}">Open topic</a></div></article>`;}
function renderCards(){const search=($("#topicSearch").value||"").trim().toLowerCase();const filter=$("#audienceFilter").value;const matches=i=>`${i[1]} ${i[2]} ${i[4]||""}`.toLowerCase().includes(search)&&(filter==="all"||i[3]===filter);const structures=content.structures.filter(matches);const algorithms=content.algorithms.filter(matches);$("#structureGrid").innerHTML=structures.length?structures.map(i=>card(i,"structure")).join(""):`<div class="empty-state">No data structures match the current filter.</div>`;$("#algorithmGrid").innerHTML=algorithms.length?algorithms.map(i=>card(i,"algorithm")).join(""):`<div class="empty-state">No algorithms match the current filter.</div>`;}
function renderTopicTabs(){$("#topicTabs").innerHTML=content.topicPages.map((t,n)=>`<button class="topic-tab ${n===0?"is-active":""}" role="tab" data-topic="${t.id}"><strong>${t.title}</strong><span>${t.audience}</span></button>`).join("");renderTopic(content.topicPages[0].id);}
function renderTopic(id){const t=content.topicPages.find(x=>x.id===id)||content.topicPages[0];document.querySelectorAll(".topic-tab").forEach(tab=>tab.classList.toggle("is-active",tab.dataset.topic===t.id));$("#topicDetail").innerHTML=`<span class="pill green">${t.audience}</span><h3 style="margin-top:10px">${t.title}</h3><p class="lede">${t.definition}</p><div class="detail-grid"><div class="mini-panel"><h4>Visual Model</h4><p>${t.analogy}</p></div><div class="mini-panel"><h4>Where It Appears</h4><ul>${t.uses.map(u=>`<li>${u}</li>`).join("")}</ul></div></div><div class="table-wrap"><table><thead><tr><th>Operation</th><th>Cost</th><th>Meaning</th></tr></thead><tbody>${t.operations.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join("")}</tbody></table></div><div class="detail-grid"><div><pre><code>Python\n${esc(t.codePython)}</code></pre></div><div><pre><code>TypeScript\n${esc(t.codeTs)}</code></pre></div></div><div class="mini-panel" style="margin-top:14px"><h4>Common Mistakes</h4><ul>${t.mistakes.map(m=>`<li>${m}</li>`).join("")}</ul></div>`;}
function renderPaths(){$("#pathGrid").innerHTML=content.paths.map(p=>`<article class="path-card"><h3>${p.title}</h3><p>${p.text}</p><ol>${p.steps.map(s=>`<li>${s}</li>`).join("")}</ol></article>`).join("");}
function renderUses(){$("#useGrid").innerHTML=content.uses.map(([t,x])=>`<article class="use-card"><span class="pill blue">Real system</span><h3 style="margin-top:10px">${t}</h3><p>${x}</p></article>`).join("");}
function renderExercises(){$("#exerciseGrid").innerHTML=content.exercises.map(([t,x])=>`<article class="exercise-card"><strong>${t}</strong><p>${x}</p></article>`).join("");}
function table(h,rows){return `<table><thead><tr>${h.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table>`;}
function renderReference(){$("#bigOTable").innerHTML=table(["Notation","Growth","Example"],content.bigO);$("#comparisonTable").innerHTML=table(["Structure","Strength","Tradeoff","Use"],content.comparison);$("#glossaryList").innerHTML=content.glossary.map(([term,text])=>`<div><strong>${term}</strong><p>${text}</p></div>`).join("");}
function bind(){$("#topicSearch").addEventListener("input",renderCards);$("#audienceFilter").addEventListener("change",renderCards);document.addEventListener("click",e=>{const pb=e.target.closest("[data-progress-id]");if(pb){const id=pb.dataset.progressId;progress.has(id)?progress.delete(id):progress.add(id);save();renderCards();}const tl=e.target.closest("[data-open-topic]");if(tl)renderTopic(tl.dataset.openTopic);const tt=e.target.closest("[data-topic]");if(tt)renderTopic(tt.dataset.topic);});}
document.addEventListener("DOMContentLoaded",()=>{renderFoundations();renderCards();renderTopicTabs();renderPaths();renderUses();renderExercises();renderReference();renderProgress();bind();});
})();
