window.DSA_CONTENT={
foundations:[
{title:"What is data?",text:"Data is recorded information: names, numbers, clicks, locations, messages, pixels, and measurements. Programs become useful when they can store, compare, transform, and move data reliably.",example:"A playlist stores song titles, artists, durations, and play counts."},
{title:"What is a data structure?",text:"A data structure is an organized shape for data. The shape determines which actions are easy, which actions are slow, and which mistakes are likely.",example:"A stack makes undo easy because the latest action is always on top."},
{title:"What is an algorithm?",text:"An algorithm is a repeatable set of steps for solving a problem. Good algorithms are correct, understandable, and efficient enough for the data size.",example:"Binary search finds a word in a sorted dictionary by repeatedly cutting the search area in half."},
{title:"Why efficiency matters",text:"The difference between checking every item and using a smarter structure can decide whether a program feels instant or unusable.",example:"Finding a username in a list may take thousands of checks; finding it in a hash map is usually direct."},
{title:"Big-O without heavy math",text:"Big-O describes how work grows as input grows. It ignores tiny details and focuses on the shape of growth: constant, logarithmic, linear, linearithmic, quadratic, or exponential.",example:"O(n) means doubling the input roughly doubles the work."},
{title:"Time versus memory",text:"Many engineering decisions trade memory for speed. Caches, indexes, lookup tables, and precomputed results use extra space to answer future questions faster.",example:"A map app stores road graph data so route searches do not start from scratch every time."}
],
structures:[
["arrays","Arrays and Lists","Ordered items stored by position.","high-school","Use when order and direct indexing matter."],["strings","Strings","Sequences of characters with special parsing rules.","high-school","Use for text, identifiers, search, and formatting."],["stacks","Stacks","Last in, first out containers.","high-school","Use for undo, history, parsing, and recursion."],["queues","Queues","First in, first out containers.","high-school","Use for task lines, BFS, and event processing."],["hash-maps","Hash Maps","Key-value lookup tables.","college","Use for counting, grouping, caching, and fast lookup."],["sets","Sets","Collections of unique values.","high-school","Use for membership and duplicate removal."],["linked-lists","Linked Lists","Nodes connected by references.","college","Use when pointer manipulation matters."],["trees","Trees","Hierarchical nodes with parent-child relationships.","college","Use for folders, expressions, indexes, and UI trees."],["bst","Binary Search Trees","Trees ordered for search.","college","Use to keep searchable order when balanced."],["heaps","Heaps and Priority Queues","Structures that expose the highest or lowest priority item.","professional","Use for scheduling, ranking, and top-k queries."],["graphs","Graphs","Nodes connected by edges.","college","Use for networks, routes, dependencies, and relationships."],["tries","Tries","Prefix trees for strings.","professional","Use for autocomplete, dictionaries, and prefix search."],["union-find","Union-Find","Tracks connected groups efficiently.","professional","Use for connectivity, clustering, and grouping decisions."]
],
algorithms:[
["binary-search","Binary Search","Find a target in sorted data by halving the search area.","high-school"],["sorting","Sorting","Put items in order so later operations become easier.","high-school"],["recursion","Recursion","Solve a problem by solving smaller versions of itself.","college"],["two-pointers","Two Pointers","Move two positions through data to compare or shrink a search.","college"],["sliding-window","Sliding Window","Track a moving range through a sequence.","college"],["hashing","Hashing","Convert keys into lookup positions.","college"],["tree-traversal","Tree Traversal","Visit every node in a hierarchy in a controlled order.","college"],["graph-traversal","Graph Traversal","Explore connected relationships using BFS or DFS.","college"],["divide-conquer","Divide and Conquer","Split, solve smaller parts, then combine results.","college"],["greedy","Greedy Algorithms","Make the best local choice when that choice stays valid.","professional"],["dynamic-programming","Dynamic Programming","Reuse answers to overlapping subproblems.","professional"]
],
topicPages:[
{id:"arrays",title:"Arrays and Lists",audience:"High School",definition:"An array or list stores items in a specific order and lets you access an item by its position.",analogy:"A row of numbered lockers: if you know locker 4, you can go directly to it.",operations:[["Access by index","O(1)","Direct position lookup"],["Search unsorted","O(n)","May need to inspect each item"],["Append","O(1) amortized","Usually quick at the end"],["Insert near front","O(n)","Later items shift"]],codePython:"scores = [88, 92, 75]\nscores.append(100)\nprint(scores[1])  # 92",codeTs:"const scores = [88, 92, 75];\nscores.push(100);\nconsole.log(scores[1]); // 92",mistakes:["Confusing index with value.","Forgetting that many languages start indexes at 0.","Using repeated front insertions when a queue would fit better."],uses:["Tables","game inventories","image pixels","ordered records","menus"]},
{id:"stacks",title:"Stacks",audience:"High School",definition:"A stack stores items so the newest item is removed first.",analogy:"A stack of plates: you add and remove from the top.",operations:[["Push","O(1)","Add to top"],["Pop","O(1)","Remove from top"],["Peek","O(1)","Read top without removing"],["Search","O(n)","Stacks are not built for arbitrary lookup"]],codePython:"stack = []\nstack.append(\"open settings\")\nstack.append(\"change color\")\nlast_action = stack.pop()",codeTs:"const stack: string[] = [];\nstack.push(\"open settings\");\nstack.push(\"change color\");\nconst lastAction = stack.pop();",mistakes:["Using a stack when old items must be processed first.","Popping without checking whether it is empty.","Thinking stack means sorted."],uses:["Undo","browser back button","function calls","parentheses matching","syntax parsing"]},
{id:"hash-maps",title:"Hash Maps",audience:"College",definition:"A hash map stores key-value pairs and uses a hash function to find the likely storage position for a key.",analogy:"A labeled filing cabinet: the label sends you to the drawer directly instead of scanning every folder.",operations:[["Insert","O(1) average","Store or replace a key"],["Lookup","O(1) average","Find value by key"],["Delete","O(1) average","Remove key"],["Iterate","O(n)","Visit all entries"]],codePython:"counts = {}\nfor word in [\"red\", \"blue\", \"red\"]:\n    counts[word] = counts.get(word, 0) + 1",codeTs:"const counts = new Map<string, number>();\nfor (const word of [\"red\", \"blue\", \"red\"]) {\n  counts.set(word, (counts.get(word) ?? 0) + 1);\n}",mistakes:["Assuming keys stay in meaningful order.","Ignoring collision behavior.","Using object keys incorrectly in languages where identity matters."],uses:["Caches","user records by id","word counts","deduplication","feature flags"]},
{id:"graphs",title:"Graphs",audience:"College",definition:"A graph stores entities as nodes and relationships as edges.",analogy:"A city map: intersections are nodes and roads are edges.",operations:[["Add node","O(1)","Create an entity"],["Add edge","O(1)","Create a relationship"],["BFS/DFS","O(V + E)","Visit reachable nodes"],["Shortest path","Varies","Depends on weighted or unweighted edges"]],codePython:"graph = {\"A\": [\"B\", \"C\"], \"B\": [\"D\"], \"C\": [], \"D\": []}\nseen = set()\nstack = [\"A\"]",codeTs:"const graph = new Map<string, string[]>([\n  [\"A\", [\"B\", \"C\"]],\n  [\"B\", [\"D\"]]\n]);",mistakes:["Forgetting cycles can cause infinite traversal.","Mixing up directed and undirected edges.","Choosing a matrix when a sparse adjacency list is better."],uses:["Maps","social networks","dependencies","recommendations","permissions"]},
{id:"binary-search",title:"Binary Search",audience:"High School",definition:"Binary search finds a target in sorted data by repeatedly checking the middle and discarding the half that cannot contain the target.",analogy:"Guessing a number from 1 to 100 by asking whether it is higher or lower.",operations:[["Middle check","O(1)","Inspect current midpoint"],["Search","O(log n)","Halve the remaining range"],["Requires sorting","Precondition","Data must be ordered"]],codePython:"def binary_search(nums, target):\n    lo, hi = 0, len(nums) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if nums[mid] == target:\n            return mid\n        if nums[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1",codeTs:"function binarySearch(nums: number[], target: number): number {\n  let lo = 0, hi = nums.length - 1;\n  while (lo <= hi) {\n    const mid = Math.floor((lo + hi) / 2);\n    if (nums[mid] === target) return mid;\n    if (nums[mid] < target) lo = mid + 1;\n    else hi = mid - 1;\n  }\n  return -1;\n}",mistakes:["Using it on unsorted data.","Off-by-one loop boundaries.","Not updating low or high after checking the middle."],uses:["Search boxes with sorted indexes","threshold decisions","version lookup","range queries"]},
{id:"bfs",title:"Breadth-First Search",audience:"College",definition:"BFS explores a graph or tree layer by layer using a queue.",analogy:"News spreading from one person to all immediate friends, then friends of friends.",operations:[["Enqueue start","O(1)","Begin the frontier"],["Visit neighbors","O(V + E)","Each node and edge is considered"],["Find shortest unweighted path","O(V + E)","First visit is the shallowest route"]],codePython:"from collections import deque\n\ndef bfs(graph, start):\n    seen = {start}\n    q = deque([start])\n    while q:\n        node = q.popleft()\n        for nxt in graph[node]:\n            if nxt not in seen:\n                seen.add(nxt)\n                q.append(nxt)",codeTs:"function bfs(graph: Map<string, string[]>, start: string) {\n  const seen = new Set([start]);\n  const queue = [start];\n  while (queue.length) {\n    const node = queue.shift()!;\n    for (const next of graph.get(node) ?? []) {\n      if (!seen.has(next)) {\n        seen.add(next);\n        queue.push(next);\n      }\n    }\n  }\n}",mistakes:["Forgetting the seen set.","Using BFS for weighted shortest paths.","Using array shift at large scale in JavaScript without a queue index."],uses:["Shortest unweighted routes","level order tree traversal","web crawlers","dependency expansion"]}
],
paths:[{title:"High School",text:"Build intuition first. Use visuals, analogies, and short code snippets after the model makes sense.",steps:["Foundations","Arrays and strings","Stacks and queues","Binary search","Sorting demos","Mini projects"]},{title:"College",text:"Connect mental models to vocabulary, complexity, pseudocode, and course-style reasoning.",steps:["Big-O","Core structures","Recursion","Trees and graphs","BFS/DFS","Greedy and DP"]},{title:"Young Professionals",text:"Focus on tradeoffs in production systems and how structures support product behavior.",steps:["Hash maps and caches","Queues and workers","Trees and indexes","Graphs and dependencies","Heaps and ranking","Design tradeoffs"]}],
uses:[["Browser history","Stacks keep the newest page on top so Back can return to the previous page."],["Print jobs","Queues process the oldest waiting job first."],["Caching","Hash maps store answers by key so repeated lookups are fast."],["Autocomplete","Tries organize words by shared prefixes."],["Database indexes","Tree-like structures keep records searchable without scanning every row."],["Maps and routing","Graphs model roads, stations, and connections."],["Social networks","Graphs model friendships, follows, blocks, groups, and recommendations."],["Schedulers","Priority queues decide which job, alert, or message should run next."],["Text search","Indexes, hashing, ranking, and graph signals combine to find relevant results."]],
exercises:[["Concept check","Explain why a hash map is better than an array for looking up users by id."],["Trace the algorithm","Walk through binary search for target 14 in [2, 5, 8, 11, 14, 20]."],["Predict the output","Given pushes A, B, C and two pops, what remains on the stack?"],["Debug the explanation","A graph traversal without a seen set may repeat forever. Explain why."],["Compare approaches","When would a queue be better than a stack for processing support tickets?"],["Mini project","Build a small cache simulator with a maximum size and eviction rule."]],
bigO:[["O(1)","Constant","Lookup array item by index"],["O(log n)","Logarithmic","Binary search"],["O(n)","Linear","Scan a list once"],["O(n log n)","Linearithmic","Efficient comparison sorting"],["O(n^2)","Quadratic","Compare every pair"],["O(2^n)","Exponential","Try every subset"]],
comparison:[["Array/List","Fast index access","Slow front insert","Ordered collections"],["Stack","Simple recent-item access","Only top is easy","Undo and parsing"],["Queue","Fair processing order","Middle access is awkward","Tasks and BFS"],["Hash Map","Fast key lookup","Order is not the point","Caches and counts"],["Tree","Models hierarchy","Can become complex","Folders and indexes"],["Graph","Models relationships","Cycles require care","Routes and networks"]],
glossary:[["Traversal","Visiting items in a structure in a planned order."],["Index","A position or lookup aid that makes access faster."],["Collision","When two keys map to the same hash bucket."],["Frontier","The next group of nodes waiting to be explored."],["Memoization","Saving previous answers so repeated work is avoided."]]
};
