(function(){
const instances={};
function sketchFactory(hostId,setupState,drawState){return function(p){const host=document.getElementById(hostId);let state=setupState();p.setup=()=>p.createCanvas(Math.max(300,host.clientWidth),250).parent(host);p.windowResized=()=>p.resizeCanvas(Math.max(300,host.clientWidth),250);p.draw=()=>{p.background("#f8fafc");drawState(p,state);};p.control=action=>{const next=state.handle(action,state);if(next)state=next;};};}
function label(p,text,x,y,size=13){p.noStroke();p.fill("#172026");p.textSize(size);p.textAlign(p.CENTER,p.CENTER);p.text(text,x,y);}
function stackSetup(){return{values:["A","B","C"],next:4,handle(a,s){if(a==="push"&&s.values.length<6)s.values.push(String.fromCharCode(64+s.next++));if(a==="pop")s.values.pop();if(a==="reset")return stackSetup();}};}
function stackDraw(p,s){const w=120,h=34,x=p.width/2-w/2,base=208;p.stroke("#172026");p.strokeWeight(2);p.line(x-12,base+8,x+w+12,base+8);s.values.forEach((v,i)=>{const y=base-(i+1)*h;p.fill(i===s.values.length-1?"#bfdbfe":"#fff");p.rect(x,y,w,h,6);label(p,v,x+w/2,y+h/2);});label(p,"top",x+w+34,base-s.values.length*h+h/2,12);}
function sortSetup(){return{values:[72,28,90,45,60,18,84],i:0,j:1,min:0,auto:false,handle(a,s){if(a==="reset")return sortSetup();if(a==="auto")s.auto=!s.auto;if(a==="step")sortStep(s);}};}
function sortStep(s){if(s.i>=s.values.length-1)return;if(s.j<s.values.length){if(s.values[s.j]<s.values[s.min])s.min=s.j;s.j++;}else{[s.values[s.i],s.values[s.min]]=[s.values[s.min],s.values[s.i]];s.i++;s.min=s.i;s.j=s.i+1;}}
function sortDraw(p,s){if(s.auto&&p.frameCount%24===0)sortStep(s);const gap=10,w=(p.width-60-gap*(s.values.length-1))/s.values.length;s.values.forEach((v,i)=>{const h=v*1.7,x=30+i*(w+gap),y=210-h;p.noStroke();p.fill(i<s.i?"#99f6e4":i===s.min?"#fde68a":i===s.j?"#bfdbfe":"#fff");p.rect(x,y,w,h,6);p.stroke("#172026");p.noFill();p.rect(x,y,w,h,6);label(p,String(v),x+w/2,226,12);});label(p,"Selection sort state",p.width/2,24,13);}
function graphSetup(mode="bfs"){return{mode,visited:["A"],frontier:["A"],edges:{A:["B","C"],B:["D","E"],C:["F"],D:[],E:["F"],F:[]},handle(a,s){if(a==="reset")return graphSetup(s.mode);if(a==="bfs"||a==="dfs"){s.mode=a;graphStep(s);}}};}
function graphStep(s){if(!s.frontier.length)return;const n=s.mode==="bfs"?s.frontier.shift():s.frontier.pop();(s.edges[n]||[]).forEach(next=>{if(!s.visited.includes(next)){s.visited.push(next);s.frontier.push(next);}});}
function graphDraw(p,s){const cx=p.width/2,qw=p.width/4;const pos={A:[cx,44],B:[cx-qw*0.8,118],C:[cx+qw*0.8,118],D:[cx-qw*1.3,192],E:[cx-qw*0.3,192],F:[cx+qw*0.8,192]};p.stroke("#94a3b8");Object.entries(s.edges).forEach(([f,tos])=>tos.forEach(to=>p.line(pos[f][0],pos[f][1],pos[to][0],pos[to][1])));Object.entries(pos).forEach(([n,xy])=>{p.fill(s.visited.includes(n)?"#99f6e4":"#fff");p.stroke("#172026");p.circle(xy[0],xy[1],42);label(p,n,xy[0],xy[1],14);});label(p,`${s.mode.toUpperCase()} visited: ${s.visited.join(", ")}`,p.width/2,232,12);}
function hashSetup(){return{keys:["cat","tea","map"],options:["sun","dog","act","pen","car","team"],highlight:null,handle(a,s){if(a==="reset")return hashSetup();if(a==="add"){const next=s.options.shift();if(next)s.keys.push(next);s.highlight=next||null;}if(a==="find")s.highlight=s.keys[Math.floor(Math.random()*s.keys.length)];}};}
function bucket(k){return k.split("").reduce((sum,c)=>sum+c.charCodeAt(0),0)%5;}
function hashDraw(p,s){const buckets=[[],[],[],[],[]];s.keys.forEach(k=>buckets[bucket(k)].push(k));buckets.forEach((items,i)=>{const x=24+i*((p.width-48)/5),w=(p.width-70)/5;p.fill("#fff");p.stroke("#172026");p.rect(x,56,w,146,6);label(p,`B${i}`,x+w/2,36,12);items.forEach((item,j)=>{p.fill(item===s.highlight?"#fde68a":"#bfdbfe");p.rect(x+8,76+j*30,w-16,22,5);label(p,item,x+w/2,87+j*30,12);});});label(p,"hash(key) % 5 chooses a bucket",p.width/2,226,12);}
function queueSetup(){return{values:["A","B","C"],next:4,handle(a,s){if(a==="enqueue"&&s.values.length<7)s.values.push(String.fromCharCode(64+s.next++));if(a==="dequeue")s.values.shift();if(a==="reset")return queueSetup();}};}
function queueDraw(p,s){const w=54,gap=8,total=s.values.length*w+Math.max(0,s.values.length-1)*gap;let x=p.width/2-total/2;s.values.forEach((v,i)=>{p.fill(i===0?"#fde68a":i===s.values.length-1?"#bfdbfe":"#fff");p.stroke("#172026");p.rect(x,105,w,48,6);label(p,v,x+w/2,129,14);x+=w+gap;});label(p,"front",p.width/2-total/2+27,82,12);label(p,"back",p.width/2+total/2-27,178,12);}
function binarySetup(){return{values:[3,7,11,14,18,22,31,40],targets:[18,7,31,14],targetIndex:0,lo:0,hi:7,found:null,handle(a,s){if(a==="reset")return binarySetup();if(a==="target"){const n=binarySetup();n.targetIndex=(s.targetIndex+1)%s.targets.length;return n;}if(a==="step")binaryStep(s);}};}
function binaryStep(s){if(s.found!==null||s.lo>s.hi)return;const mid=Math.floor((s.lo+s.hi)/2),target=s.targets[s.targetIndex];if(s.values[mid]===target)s.found=mid;else if(s.values[mid]<target)s.lo=mid+1;else s.hi=mid-1;}
function binaryDraw(p,s){const target=s.targets[s.targetIndex],w=Math.min(58,(p.width-40)/s.values.length),start=p.width/2-w*s.values.length/2,mid=Math.floor((s.lo+s.hi)/2);s.values.forEach((v,i)=>{const x=start+i*w,active=i>=s.lo&&i<=s.hi;p.fill(s.found===i?"#99f6e4":i===mid&&active?"#fde68a":active?"#fff":"#e2e8f0");p.stroke("#172026");p.rect(x,102,w-4,44,6);label(p,String(v),x+w/2-2,124,13);});label(p,`target: ${target}`,p.width/2,50,14);label(p,s.found!==null?`found at index ${s.found}`:`search range: ${s.lo} to ${s.hi}`,p.width/2,188,13);}
function init(){if(!window.p5){document.querySelectorAll(".canvas-host").forEach(h=>h.innerHTML='<p style="padding:18px">p5.js could not load. Check the network connection and reload the page.</p>');return;}instances.stack=new p5(sketchFactory("stackCanvas",stackSetup,stackDraw));instances.sort=new p5(sketchFactory("sortCanvas",sortSetup,sortDraw));instances.graph=new p5(sketchFactory("graphCanvas",graphSetup,graphDraw));instances.hash=new p5(sketchFactory("hashCanvas",hashSetup,hashDraw));instances.queue=new p5(sketchFactory("queueCanvas",queueSetup,queueDraw));instances.binary=new p5(sketchFactory("binaryCanvas",binarySetup,binaryDraw));}
document.addEventListener("DOMContentLoaded",()=>{setTimeout(init,80);document.addEventListener("click",e=>{const b=e.target.closest("[data-demo]");if(!b)return;const instance=instances[b.dataset.demo];if(instance&&instance.control)instance.control(b.dataset.action);});});
})();
